name: Update shared packages on Injective-ui

on:
  push:
    branches:
      - master
      - ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout injective-ui repository
      uses: actions/checkout@v2
      with:
        repository: InjectiveLabs/injective-ui
        path: injective-ui
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd injective-ui
        cd layer
        yarn install

    - name: Create branch
      run: |
        cd injective-ui
        git checkout -b update-from-shared-packages

    - name: Commit changes
      run: |
        cd injective-ui
        git add .
        git commit -m "chore: update from shared-packages"

    - name: Push changes
      run: |
        cd injective-ui
        git push origin update-from-shared-packages

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"
        gh pr create --repo InjectiveLabs/injective-ui --head update-from-shared-packages --base dev --title "Package bump" --body "This is an automated pull request created by GitHub Actions."

    - name: Cleanup
      run: |
        cd injective-ui
        git branch -D update-from-shared-packages
