name: Package bump Layer

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout injective-ui repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: injective-ui
          token: ${{ secrets.GH_TOKEN }}
          repository: InjectiveLabs/injective-ui

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          cd injective-ui
          cd layer
          yarn install

      - name: Commit changes
        run: |
          cd injective-ui
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "chore: package bump"

      - name: Push changes
        run: |
          cd injective-ui
          git push origin master
