name: Package bump Mito

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mito-ui repository
        uses: actions/checkout@v4
        with:
          path: mito-ui
          fetch-depth: 0
          repository: mitoFinance/mito-ui
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          cd mito-ui
          yarn install

      - name: Commit changes
        run: |
          cd mito-ui
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "chore: package bump"

      - name: Push changes
        run: |
          cd mito-ui
          git push origin dev
