name: Package bump layer

on:
  push:
    branches:
      - master
      - ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mito-ui repository
        uses: actions/checkout@v2
        with:
          repository: mitoFinance/mito-ui
          path: mito-ui
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      # - name: Install dependencies
      #   run: |
      #     cd mito-ui
      #     yarn install

      # - name: Commit changes
      #   run: |
      #     cd mito-ui
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"
      #     git add .
      #     git commit -m "chore: package bump"

      # - name: Push changes
      #   run: |
      #     cd mito-ui
      #     git push origin dev

      - name: Get Pull Request Number
        run: |
          echo ${{ github.event.issue.number }}
          echo ${{ github }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
